sudo: required
services:
  -docker

before_install:
  - docker build -t mthc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mthc/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "Docker React app"
  environment: "DockerReactapp-env"
  bucket_name: "elasticbeanstalk-eu-west-1-634113382203"
  bucket_path: "Docker React app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY



